version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cbr_bot_postgres
    environment:
      POSTGRES_DB: cbr_bot
      POSTGRES_USER: cbr_user
      POSTGRES_PASSWORD: cbr_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - cbr_bot_network
    restart: unless-stopped

  # CBR Bot Application
  cbr-bot:
    build: .
    container_name: cbr_bot_app
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - DATABASE_URL=postgresql://cbr_user:cbr_password@postgres:5432/cbr_bot
      - MONITORING_INTERVAL=${MONITORING_INTERVAL:-2700000}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS:-1856156198,145328014}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Playwright environment variables
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
      - PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/bin/google-chrome
      - DISPLAY=:99
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      # Sharp environment variables
      - SHARP_IGNORE_GLOBAL_LIBVIPS=1
      - npm_config_sharp_binary_host=""
      - npm_config_sharp_libvips_binary_host=""
    depends_on:
      - postgres
    networks:
      - cbr_bot_network
    restart: unless-stopped
    # Добавляем привилегии для работы с браузером
    privileged: true
    # Добавляем shared memory для браузера
    shm_size: '2gb'
    # Добавляем возможности для работы с браузером
    cap_add:
      - SYS_ADMIN
    # Отключаем песочницу для Chrome
    security_opt:
      - seccomp:unconfined

volumes:
  postgres_data:
  pgadmin_data:

networks:
  cbr_bot_network:
    driver: bridge
