version: '3.8'

services:
  # CBR Bot Application with Supabase
  cbr-bot:
    build: .
    container_name: cbr_bot_app
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - BOT_TOKEN=${BOT_TOKEN}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      # Supabase configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # Monitoring and admin settings
      - MONITORING_INTERVAL=${MONITORING_INTERVAL:-2700000}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Proxy settings (if needed)
      - PROXY_ENABLED=${PROXY_ENABLED:-false}
      - PROXY_SERVER=${PROXY_SERVER}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - PROXY_BYPASS=${PROXY_BYPASS}
      # Playwright environment variables
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
      - PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/bin/google-chrome
      - DISPLAY=:99

    networks:
      - cbr_bot_network
    restart: unless-stopped
    # Добавляем привилегии для работы с браузером
    privileged: true
    # Добавляем shared memory для браузера
    shm_size: '2gb'
    # Добавляем возможности для работы с браузером
    cap_add:
      - SYS_ADMIN
    # Отключаем песочницу для Chrome
    security_opt:
      - seccomp:unconfined

networks:
  cbr_bot_network:
    driver: bridge